apiVersion: v1
kind: Secret
metadata:
  name: identity-secret
  namespace: app
type: Opaque
stringData:
  # DB
  DBMS_CONNECTION: jdbc:mysql://mysql-identity.infra.svc.cluster.local:3306/identity_service
  DBMS_USERNAME: root
  DBMS_PASSWORD: root
  # JWT
  JWT_SIGNERKEY: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  JWT_VALID_DURATION: "3600"
  JWT_REFRESHABLE_DURATION: "36000"