apiVersion: v1
kind: Secret
metadata:
  name: identity-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mysql-username: {{ .Values.db.username | b64enc }}
  mysql-password: {{ .Values.db.password | b64enc }}
