apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-identity
  namespace: infra
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql-identity
  template:
    metadata:
      labels:
        app: mysql-identity
    spec:
      securityContext:
        fsGroup: 65534
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_DATABASE
          value: identity_service
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: nfs-pvc