apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: {{ .Values.namespace }}
data:
  application.yml: |
    server:
      port: 8082
      servlet:
        context-path: /notification
    spring:
      application:
        name: notification-service
      data:
        mongodb:
          uri: {{ .Values.mongodb.uri }}
      kafka:
        bootstrap-servers: {{ .Values.kafka.bootstrapServers }}
        consumer:
          group-id: notification-group
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          properties:
            spring.json.trusted.packages: "*"
    notification:
      email:
        brevo-url: https://api.brevo.com
