apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: app
data:
  application.yml: |
    server:
      port: 8888
    app:
      api-prefix: /api/v1
    spring:
      application:
        name: api-gateway
      cloud:
        gateway:
          routes:
            - id: identity_service
              uri: http://identity-service.app.svc.cluster.local:8080
              predicates:
                - Path=${app.api-prefix}/identity/**
              filters:
                - StripPrefix=2
            - id: profile_service
              uri: http://profile-service.app.svc.cluster.local:8081
              predicates:
                - Path=${app.api-prefix}/profile/users/**
              filters:
                - StripPrefix=2
            - id: notification_service
              uri: http://notification-service.app.svc.cluster.local:8082
              predicates:
                - Path=${app.api-prefix}/notification/**
              filters:
                - StripPrefix=2
            - id: post_service
              uri: http://post-service.app.svc.cluster.local:8083
              predicates:
                - Path=${app.api-prefix}/post/**
              filters:
                - StripPrefix=2