apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: hoangvu42/api-gateway:v1
        ports:
          - containerPort: 8888
        envFrom:
          - configMapRef:
              name: api-gateway-config
          - secretRef:
              name: api-gateway-secret
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 15
          periodSeconds: 5