apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: app
type: Opaque
data:
  jwt-signerKey: <base64_signerKey>
  jwt-valid-duration: <base64_3600>
  jwt-refreshable-duration: <base64_36000>