apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  jwt-signerKey: {{ .Values.jwt.signerKey }}
  jwt-valid-duration: {{ .Values.jwt.validDuration }}
  jwt-refreshable-duration: {{ .Values.jwt.refreshableDuration }}
