apiVersion: v1
kind: Secret
metadata:
  name: profile-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  neo4j-username: {{ .Values.neo4j.username | b64enc }}
  neo4j-password: {{ .Values.neo4j.password | b64enc }}
