apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: app
data:
  application.yml: |
    server:
      port: 8082
      servlet:
        context-path: /notification

    spring:
      application:
        name: notification-service

      data:
        mongodb:
          uri: ${MONGODB_CONNECTION}

      kafka:
        bootstrap-servers: kafka-service.app.svc.cluster.local:9094
        consumer:
          group-id: notification-group
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          properties:
            spring.json.trusted.packages: "*"

    notification:
      email:
        brevo-url: https://api.brevo.com
        brevo-apikey: ${BREVO_APIKEY}