apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: app
type: Opaque
stringData:
  MONGODB_CONNECTION: "mongodb://root:root@mongo-notification.app.svc.cluster.local:27017/notification-service?authSource=admin"
  BREVO_APIKEY: "<your-brevo-apikey>"