apiVersion: v1
kind: Secret
metadata:
  name: post-secret
  namespace: app
type: Opaque
stringData:
  MONGODB_CONNECTION: "mongodb://root:root@mongo-post.app.svc.cluster.local:27017/post-service?authSource=admin"